typedef unsigned char undefined1;
typedef unsigned char byte;
typedef unsigned char undefined;
typedef unsigned char bool;
#define true 1
#define false 0
typedef unsigned short undefined2;
typedef unsigned short ushort;
typedef unsigned short word;
typedef unsigned int undefined4;
typedef unsigned int uint;
typedef unsigned int dword;
typedef unsigned int ulong;
typedef unsigned __int64 undefined8;
typedef unsigned __int64 ulonglong;
typedef unsigned __int64 qword;
typedef __int64 longlong;
typedef int (*code)();
typedef unsigned char U8;
typedef unsigned short U16;
typedef unsigned int U32;
typedef unsigned __int64 U64;
typedef signed char S8;
typedef signed short S16;
typedef signed int S32;
typedef __int64 S64;
typedef struct { U64 lo, hi; } V16;
extern int fn_82F68CC0();
extern unsigned int lbl_8329F068;
extern unsigned int lbl_8329F070;
extern unsigned int lbl_8329F078;
extern unsigned int lbl_8329F080;
extern unsigned int uRam8329f06c;
extern unsigned int uRam8329f074;
extern unsigned int uRam8329f07c;
extern unsigned int uRam8329f094;
extern unsigned int uRam8329f600;
extern unsigned int uStack_100;
extern unsigned int uStack_101;
extern unsigned int uStack_102;
extern unsigned int uStack_103;
extern unsigned int uStack_104;
extern unsigned int uStack_105;
extern unsigned int uStack_106;
extern unsigned int uStack_107;
extern unsigned int uStack_108;
extern unsigned int uStack_109;
extern unsigned int uStack_10a;
extern unsigned int uStack_10b;
extern unsigned int uStack_10c;
extern unsigned int uStack_10d;
extern unsigned int uStack_10e;
extern unsigned int uStack_10f;
extern unsigned int uStack_110;
extern unsigned int uStack_111;
extern unsigned int uStack_112;
extern unsigned int uStack_113;
extern unsigned int uStack_114;
extern unsigned int uStack_115;
extern unsigned int uStack_116;
extern unsigned int uStack_117;
extern unsigned int uStack_118;
extern unsigned int uStack_119;
extern unsigned int uStack_11a;
extern unsigned int uStack_11b;
extern unsigned int uStack_11c;
extern unsigned int uStack_11d;
extern unsigned int uStack_11e;
extern unsigned int uStack_11f;
extern unsigned int uStack_120;
extern unsigned int uStack_121;
extern unsigned int uStack_122;
extern unsigned int uStack_123;
extern unsigned int uStack_124;
extern unsigned int uStack_125;
extern unsigned int uStack_126;
extern unsigned int uStack_127;
extern unsigned int uStack_128;
extern unsigned int uStack_129;
extern unsigned int uStack_12a;
extern unsigned int uStack_12b;
extern unsigned int uStack_12c;
extern unsigned int uStack_12d;
extern unsigned int uStack_12e;
extern unsigned int uStack_12f;
extern unsigned int uStack_130;
extern unsigned int uStack_131;
extern unsigned int uStack_132;
extern unsigned int uStack_133;
extern unsigned int uStack_134;
extern unsigned int uStack_135;
extern unsigned int uStack_136;
extern unsigned int uStack_137;
extern unsigned int uStack_138;
extern unsigned int uStack_139;
extern unsigned int uStack_13a;
extern unsigned int uStack_13b;
extern unsigned int uStack_13c;
extern unsigned int uStack_13d;
extern unsigned int uStack_13e;
extern unsigned int uStack_13f;
extern unsigned int uStack_140;
extern unsigned int uStack_b1;
extern unsigned int uStack_b2;
extern unsigned int uStack_b3;
extern unsigned int uStack_b4;
extern unsigned int uStack_b5;
extern unsigned int uStack_b6;
extern unsigned int uStack_b7;
extern unsigned int uStack_b8;
extern unsigned int uStack_b9;
extern unsigned int uStack_ba;
extern unsigned int uStack_bb;
extern unsigned int uStack_bc;
extern unsigned int uStack_bd;
extern unsigned int uStack_be;
extern unsigned int uStack_bf;
extern unsigned int uStack_c0;
extern unsigned int uStack_c1;
extern unsigned int uStack_c2;
extern unsigned int uStack_c3;
extern unsigned int uStack_c4;
extern unsigned int uStack_c5;
extern unsigned int uStack_c6;
extern unsigned int uStack_c7;
extern unsigned int uStack_c8;
extern unsigned int uStack_c9;
extern unsigned int uStack_ca;
extern unsigned int uStack_cb;
extern unsigned int uStack_cc;
extern unsigned int uStack_cd;
extern unsigned int uStack_ce;
extern unsigned int uStack_cf;
extern unsigned int uStack_d0;
extern unsigned int uStack_d1;
extern unsigned int uStack_d2;
extern unsigned int uStack_d3;
extern unsigned int uStack_d4;
extern unsigned int uStack_d5;
extern unsigned int uStack_d6;
extern unsigned int uStack_d7;
extern unsigned int uStack_d8;
extern unsigned int uStack_d9;
extern unsigned int uStack_da;
extern unsigned int uStack_db;
extern unsigned int uStack_dc;
extern unsigned int uStack_dd;
extern unsigned int uStack_de;
extern unsigned int uStack_df;
extern unsigned int uStack_e0;
extern unsigned int uStack_e1;
extern unsigned int uStack_e2;
extern unsigned int uStack_e3;
extern unsigned int uStack_e4;
extern unsigned int uStack_e5;
extern unsigned int uStack_e6;
extern unsigned int uStack_e7;
extern unsigned int uStack_e8;
extern unsigned int uStack_e9;
extern unsigned int uStack_ea;
extern unsigned int uStack_eb;
extern unsigned int uStack_ec;
extern unsigned int uStack_ed;
extern unsigned int uStack_ee;
extern unsigned int uStack_ef;
extern unsigned int uStack_f0;
extern unsigned int uStack_f1;
extern unsigned int uStack_f2;
extern unsigned int uStack_f3;
extern unsigned int uStack_f4;
extern unsigned int uStack_f5;
extern unsigned int uStack_f6;
extern unsigned int uStack_f7;
extern unsigned int uStack_f8;
extern unsigned int uStack_f9;
extern unsigned int uStack_fa;
extern unsigned int uStack_fb;
extern unsigned int uStack_fc;
extern unsigned int uStack_fd;
extern unsigned int uStack_fe;
extern unsigned int uStack_ff;


void fn_82F2C030(void)

{
  undefined1 uStack_140;
  undefined1 uStack_13f;
  undefined1 uStack_13e;
  undefined1 uStack_13d;
  undefined1 uStack_13c;
  undefined1 uStack_13b;
  undefined1 uStack_13a;
  undefined1 uStack_139;
  undefined1 uStack_138;
  undefined1 uStack_137;
  undefined1 uStack_136;
  undefined1 uStack_135;
  undefined1 uStack_134;
  undefined1 uStack_133;
  undefined1 uStack_132;
  undefined1 uStack_131;
  undefined1 uStack_130;
  undefined1 uStack_12f;
  undefined1 uStack_12e;
  undefined1 uStack_12d;
  undefined1 uStack_12c;
  undefined1 uStack_12b;
  undefined1 uStack_12a;
  undefined1 uStack_129;
  undefined1 uStack_128;
  undefined1 uStack_127;
  undefined1 uStack_126;
  undefined1 uStack_125;
  undefined1 uStack_124;
  undefined1 uStack_123;
  undefined1 uStack_122;
  undefined1 uStack_121;
  undefined1 uStack_120;
  undefined1 uStack_11f;
  undefined1 uStack_11e;
  undefined1 uStack_11d;
  undefined1 uStack_11c;
  undefined1 uStack_11b;
  undefined1 uStack_11a;
  undefined1 uStack_119;
  undefined1 uStack_118;
  undefined1 uStack_117;
  undefined1 uStack_116;
  undefined1 uStack_115;
  undefined1 uStack_114;
  undefined1 uStack_113;
  undefined1 uStack_112;
  undefined1 uStack_111;
  undefined1 uStack_110;
  undefined1 uStack_10f;
  undefined1 uStack_10e;
  undefined1 uStack_10d;
  undefined1 uStack_10c;
  undefined1 uStack_10b;
  undefined1 uStack_10a;
  undefined1 uStack_109;
  undefined1 uStack_108;
  undefined1 uStack_107;
  undefined1 uStack_106;
  undefined1 uStack_105;
  undefined1 uStack_104;
  undefined1 uStack_103;
  undefined1 uStack_102;
  undefined1 uStack_101;
  undefined1 uStack_100;
  undefined1 uStack_ff;
  undefined1 uStack_fe;
  undefined1 uStack_fd;
  undefined1 uStack_fc;
  undefined1 uStack_fb;
  undefined1 uStack_fa;
  undefined1 uStack_f9;
  undefined1 uStack_f8;
  undefined1 uStack_f7;
  undefined1 uStack_f6;
  undefined1 uStack_f5;
  undefined1 uStack_f4;
  undefined1 uStack_f3;
  undefined1 uStack_f2;
  undefined1 uStack_f1;
  undefined1 uStack_f0;
  undefined1 uStack_ef;
  undefined1 uStack_ee;
  undefined1 uStack_ed;
  undefined1 uStack_ec;
  undefined1 uStack_eb;
  undefined1 uStack_ea;
  undefined1 uStack_e9;
  undefined1 uStack_e8;
  undefined1 uStack_e7;
  undefined1 uStack_e6;
  undefined1 uStack_e5;
  undefined1 uStack_e4;
  undefined1 uStack_e3;
  undefined1 uStack_e2;
  undefined1 uStack_e1;
  undefined1 uStack_e0;
  undefined1 uStack_df;
  undefined1 uStack_de;
  undefined1 uStack_dd;
  undefined1 uStack_dc;
  undefined1 uStack_db;
  undefined1 uStack_da;
  undefined1 uStack_d9;
  undefined1 uStack_d8;
  undefined1 uStack_d7;
  undefined1 uStack_d6;
  undefined1 uStack_d5;
  undefined1 uStack_d4;
  undefined1 uStack_d3;
  undefined1 uStack_d2;
  undefined1 uStack_d1;
  undefined1 uStack_d0;
  undefined1 uStack_cf;
  undefined1 uStack_ce;
  undefined1 uStack_cd;
  undefined1 uStack_cc;
  undefined1 uStack_cb;
  undefined1 uStack_ca;
  undefined1 uStack_c9;
  undefined1 uStack_c8;
  undefined1 uStack_c7;
  undefined1 uStack_c6;
  undefined1 uStack_c5;
  undefined1 uStack_c4;
  undefined1 uStack_c3;
  undefined1 uStack_c2;
  undefined1 uStack_c1;
  undefined1 uStack_c0;
  undefined1 uStack_bf;
  undefined1 uStack_be;
  undefined1 uStack_bd;
  undefined1 uStack_bc;
  undefined1 uStack_bb;
  undefined1 uStack_ba;
  undefined1 uStack_b9;
  undefined1 uStack_b8;
  undefined1 uStack_b7;
  undefined1 uStack_b6;
  undefined1 uStack_b5;
  undefined1 uStack_b4;
  undefined1 uStack_b3;
  undefined1 uStack_b2;
  undefined1 uStack_b1;
  char *pcStack_b0;
  char *pcStack_ac;
  char *pcStack_a8;
  char *pcStack_a4;
  char *pcStack_a0;
  
  uStack_d0 = 0x10;
  uStack_ce = 0x10;
  uStack_cf = 0;
  uStack_cc = 0x10;
  uStack_cb = 4;
  uStack_cd = 2;
  uStack_ca = 0x10;
  uStack_c9 = 6;
  uStack_c8 = 0x10;
  uStack_c7 = 8;
  uStack_c6 = 0x10;
  uStack_c5 = 10;
  uStack_c4 = 0x10;
  uStack_c3 = 0xc;
  uStack_c2 = 0x10;
  uStack_c1 = 0xe;
  uStack_140 = 0;
  uStack_13f = 1;
  uStack_13e = 0x10;
  uStack_13d = 0x11;
  uStack_13c = 4;
  uStack_13b = 5;
  uStack_13a = 0x14;
  uStack_139 = 0x15;
  uStack_138 = 8;
  uStack_137 = 9;
  uStack_136 = 0x18;
  uStack_135 = 0x19;
  uStack_134 = 0xc;
  uStack_133 = 0xd;
  uStack_132 = 0x1c;
  uStack_131 = 0x1d;
  uStack_130 = 2;
  uStack_12f = 3;
  uStack_12e = 4;
  uStack_12d = 5;
  uStack_12c = 6;
  uStack_12b = 7;
  uStack_12a = 8;
  uStack_129 = 9;
  uStack_128 = 10;
  uStack_127 = 0xb;
  uStack_126 = 0xc;
  uStack_125 = 0xd;
  uStack_124 = 0xe;
  uStack_123 = 0xf;
  uStack_122 = 0x10;
  uStack_121 = 0x11;
  uStack_f0 = 0;
  uStack_ef = 1;
  uStack_ee = 2;
  uStack_ed = 3;
  uStack_ec = 4;
  uStack_eb = 5;
  uStack_ea = 6;
  uStack_e9 = 7;
  uStack_e8 = 0x10;
  uStack_11f = 1;
  uStack_11d = 5;
  uStack_100 = 2;
  uStack_e3 = 0x15;
  uStack_fe = 6;
  uStack_e7 = 0x11;
  uStack_117 = 0x11;
  uStack_e4 = 0x14;
  uStack_120 = 0;
  uStack_11e = 4;
  uStack_11c = 8;
  uRam8329f074 = 0x8325f8b0;
  lbl_8329F070 = 0x8325f8a0;
  pcStack_a0 = 
  "useliveconnections=true\r\n\r\n[ServiceMap]\r\ndefaultMask=XLS.Express.*\r\nservices=Topology,WebGateway,NotifyUser,BroadcastUp,BroadcastDown,WebGatewayTransacted\r\n\r\n[ProtocolFactory]\r\nport=1215\r\nportrange=1\r\n\r\n[DebugOptions]\r\ndefaultTimeoutMs=60000 \r\nerrorMode=Tolerant\r\nforceLogger=off\r\nminSeverity=Error\r\n\r\n[Content:ContentServer]\r\npath=Content.banjo.contentserver.v1\r\ndefaultMask=XLS.Express.*\r\nport=8200\r\n\r\n[LogonProvider]\r\n[Content:LogonProvider]\r\n\r\n[Content:DebugOptions]\r\ndefaultTimeoutMs=60000\r\nerrorMode=Tolerant\r\nforceLogger=off\r\nminSeverity=Error\r\n"
  ;
  uRam8329f094 = 0x8325f8c0;
  uStack_11b = 9;
  uStack_e6 = 0x12;
  lbl_8329F080 = 0x8325f8d0;
  uStack_11a = 0xc;
  uStack_e5 = 0x13;
  uStack_119 = 0xd;
  uStack_118 = 0x10;
  pcStack_ac = 
  "useliveconnections=true\r\n\r\n[ServiceMap]\r\ndefaultMask=XLS.Express.*\r\nservices=Topology,WebGateway,NotifyUser,BroadcastUp,BroadcastDown,WebGatewayTransacted\r\n\r\n[ProtocolFactory]\r\nport=1215\r\nportrange=1\r\n\r\n[DebugOptions]\r\ndefaultTimeoutMs=60000 \r\nerrorMode=Tolerant\r\nforceLogger=off\r\nminSeverity=Error\r\n\r\n[Content:ContentServer]\r\npath=Content.banjo.contentserver.v1\r\ndefaultMask=XLS.Express.*\r\nport=8200\r\n\r\n[LogonProvider]\r\n[Content:LogonProvider]\r\n\r\n[Content:DebugOptions]\r\ndefaultTimeoutMs=60000\r\nerrorMode=Tolerant\r\nforceLogger=off\r\nminSeverity=Error\r\n"
  ;
  lbl_8329F078 = 0x8325f8f0;
  uStack_e1 = 0x17;
  uStack_115 = 0x15;
  lbl_8329F068 = 0x8325f8e0;
  uStack_fd = 7;
  uStack_e2 = 0x16;
  uStack_ff = 3;
  uStack_116 = 0x14;
  uStack_114 = 0x18;
  uStack_112 = 0x1c;
  uStack_fc = 10;
  uStack_113 = 0x19;
  uStack_111 = 0x1d;
  uStack_fb = 0xb;
  uStack_fa = 0xe;
  uStack_f9 = 0xf;
  uStack_f8 = 0x12;
  uStack_f7 = 0x13;
  uStack_bc = 0x10;
  uStack_b4 = 0x10;
  uRam8329f06c = 0x8325f900;
  uStack_f5 = 0x17;
  uStack_c0 = 0;
  uStack_b8 = 0;
  uStack_110 = 0;
  uStack_10f = 0;
  uStack_f6 = 0x16;
  pcStack_a8 = 
  "useliveconnections=true\r\n\r\n[ServiceMap]\r\ndefaultMask=XLS.Express.*\r\nservices=Topology,WebGateway,NotifyUser,BroadcastUp,BroadcastDown,WebGatewayTransacted\r\n\r\n[ProtocolFactory]\r\nport=1215\r\nportrange=1\r\n\r\n[DebugOptions]\r\ndefaultTimeoutMs=60000 \r\nerrorMode=Tolerant\r\nforceLogger=off\r\nminSeverity=Error\r\n\r\n[Content:ContentServer]\r\npath=Content.banjo.contentserver.v1\r\ndefaultMask=XLS.Express.*\r\nport=8200\r\n\r\n[LogonProvider]\r\n[Content:LogonProvider]\r\n\r\n[Content:DebugOptions]\r\ndefaultTimeoutMs=60000\r\nerrorMode=Tolerant\r\nforceLogger=off\r\nminSeverity=Error\r\n"
  ;
  pcStack_b0 = 
  "useliveconnections=true\r\n\r\n[ServiceMap]\r\ndefaultMask=XLS.Express.*\r\nservices=Topology,WebGateway,NotifyUser,BroadcastUp,BroadcastDown,WebGatewayTransacted\r\n\r\n[ProtocolFactory]\r\nport=1215\r\nportrange=1\r\n\r\n[DebugOptions]\r\ndefaultTimeoutMs=60000 \r\nerrorMode=Tolerant\r\nforceLogger=off\r\nminSeverity=Error\r\n\r\n[Content:ContentServer]\r\npath=Content.banjo.contentserver.v1\r\ndefaultMask=XLS.Express.*\r\nport=8200\r\n\r\n[LogonProvider]\r\n[Content:LogonProvider]\r\n\r\n[Content:DebugOptions]\r\ndefaultTimeoutMs=60000\r\nerrorMode=Tolerant\r\nforceLogger=off\r\nminSeverity=Error\r\n"
  ;
  pcStack_a4 = 
  "useliveconnections=true\r\n\r\n[ServiceMap]\r\ndefaultMask=XLS.Express.*\r\nservices=Topology,WebGateway,NotifyUser,BroadcastUp,BroadcastDown,WebGatewayTransacted\r\n\r\n[ProtocolFactory]\r\nport=1215\r\nportrange=1\r\n\r\n[DebugOptions]\r\ndefaultTimeoutMs=60000 \r\nerrorMode=Tolerant\r\nforceLogger=off\r\nminSeverity=Error\r\n\r\n[Content:ContentServer]\r\npath=Content.banjo.contentserver.v1\r\ndefaultMask=XLS.Express.*\r\nport=8200\r\n\r\n[LogonProvider]\r\n[Content:LogonProvider]\r\n\r\n[Content:DebugOptions]\r\ndefaultTimeoutMs=60000\r\nerrorMode=Tolerant\r\nforceLogger=off\r\nminSeverity=Error\r\n"
  ;
  uStack_d8 = 0x18;
  uStack_d4 = 0x1c;
  uStack_ba = 0x18;
  uStack_b9 = 0x1c;
  uStack_b2 = 0x18;
  uStack_b1 = 0x1c;
  uStack_f4 = 0x1a;
  uStack_f3 = 0x1b;
  uStack_f2 = 0x1e;
  uStack_f1 = 0x1f;
  uStack_e0 = 8;
  uStack_df = 9;
  uStack_de = 10;
  uStack_dd = 0xb;
  uStack_dc = 0xc;
  uStack_db = 0xd;
  uStack_da = 0xe;
  uStack_d9 = 0xf;
  uStack_d7 = 0x19;
  uStack_d6 = 0x1a;
  uStack_d5 = 0x1b;
  uStack_d3 = 0x1d;
  uStack_d2 = 0x1e;
  uStack_d1 = 0x1f;
  uStack_bf = 4;
  uStack_be = 8;
  uStack_bd = 0xc;
  uStack_bb = 0x14;
  uStack_b7 = 4;
  uStack_b6 = 8;
  uStack_b5 = 0xc;
  uStack_b3 = 0x14;
  uStack_10e = 0xff;
  uStack_10d = 0xff;
  uStack_10c = 0xff;
  uStack_10b = 0xff;
  uStack_10a = 0xff;
  uStack_109 = 0xff;
  uStack_108 = 0xff;
  uStack_107 = 0xff;
  uStack_106 = 0xff;
  uStack_105 = 0xff;
  uStack_104 = 0xff;
  uStack_103 = 0xff;
  uStack_102 = 0xff;
  uStack_101 = 0xff;
  uRam8329f600 = 0x8325f910;
  uRam8329f07c = 0x8325f920;
  fn_82F68CC0(0x8325f8a0,&uStack_d0,0x10);
  fn_82F68CC0(uRam8329f074,&uStack_140,0x10);
  fn_82F68CC0(*(undefined4 *)(pcStack_a4 + -0xf6c),&uStack_130,0x10);
  fn_82F68CC0(*(undefined4 *)(pcStack_b0 + -0xf80),&uStack_f0,0x10);
  fn_82F68CC0(*(undefined4 *)(pcStack_ac + -0xf98),&uStack_120,0x10);
  fn_82F68CC0(*(undefined4 *)(pcStack_a0 + -0xf88),&uStack_100,0x10);
  fn_82F68CC0(*(undefined4 *)(pcStack_a8 + -0xf94),&uStack_e0,0x10);
  fn_82F68CC0(uRam8329f600,&uStack_c0,0x10);
  fn_82F68CC0(uRam8329f07c,&uStack_110,0x10);
  return;
}

