typedef unsigned char undefined1;
typedef unsigned char byte;
typedef unsigned char undefined;
typedef unsigned char bool;
#define true 1
#define false 0
typedef unsigned short undefined2;
typedef unsigned short ushort;
typedef unsigned short word;
typedef unsigned int undefined4;
typedef unsigned int uint;
typedef unsigned int dword;
typedef unsigned int ulong;
typedef unsigned __int64 undefined8;
typedef unsigned __int64 ulonglong;
typedef unsigned __int64 qword;
typedef __int64 longlong;
typedef int (*code)();
typedef unsigned char U8;
typedef unsigned short U16;
typedef unsigned int U32;
typedef unsigned __int64 U64;
typedef signed char S8;
typedef signed short S16;
typedef signed int S32;
typedef __int64 S64;
typedef struct { U64 lo, hi; } V16;
extern unsigned int fStack_30;
extern unsigned int fStack_40;
extern unsigned int fStack_50;
extern unsigned int fStack_54;
extern unsigned int fStack_60;
extern unsigned int fStack_64;
extern unsigned int fStack_70;
extern unsigned int fStack_78;
extern unsigned int fStack_80;
extern unsigned int fStack_88;
extern unsigned int fStack_8c;
extern unsigned int fStack_a4;
extern unsigned int fStack_a8;
extern unsigned int fStack_ac;
extern unsigned int fStack_b0;
extern unsigned int fStack_b4;
extern unsigned int fStack_b8;
extern unsigned int fStack_bc;
extern unsigned int fStack_c0;
extern unsigned int fStack_c4;
extern unsigned int fStack_c8;
extern unsigned int fStack_cc;
extern unsigned int fStack_d0;
extern unsigned int fStack_e0;
extern int fn_8280A668();
extern int fn_82861078();
extern unsigned int lbl_82002C5C;
extern unsigned int lbl_8201DFF0;
extern unsigned int lbl_821AAD20;
extern unsigned int uStack_34;
extern unsigned int uStack_38;
extern unsigned int uStack_44;
extern unsigned int uStack_48;
extern unsigned int uStack_58;
extern unsigned int uStack_68;
extern unsigned int uStack_74;
extern unsigned int uStack_84;
extern unsigned int uStack_90;
extern unsigned int uStack_94;
extern unsigned int uStack_98;
extern unsigned int uStack_9c;
extern unsigned int uStack_a0;


void fn_828616F0(float *param_1,undefined8 param_2,undefined8 param_3)

{
  float fStack_e0;
  float afStack_dc [3];
  float fStack_d0;
  float fStack_cc;
  float fStack_c8;
  float fStack_c4;
  float fStack_c0;
  float fStack_bc;
  float fStack_b8;
  float fStack_b4;
  float fStack_b0;
  float fStack_ac;
  float fStack_a8;
  float fStack_a4;
  undefined4 uStack_a0;
  undefined4 uStack_9c;
  undefined4 uStack_98;
  undefined4 uStack_94;
  undefined4 uStack_90;
  float fStack_8c;
  float fStack_88;
  undefined4 uStack_84;
  float fStack_80;
  float fStack_78;
  undefined4 uStack_74;
  float fStack_70;
  undefined4 uStack_68;
  float fStack_64;
  float fStack_60;
  undefined4 uStack_58;
  float fStack_54;
  float fStack_50;
  undefined4 uStack_48;
  undefined4 uStack_44;
  float fStack_40;
  undefined4 uStack_38;
  undefined4 uStack_34;
  float fStack_30;
  
  fn_8280A668((double)(*param_1 * lbl_82002C5C * lbl_8201DFF0),param_1,&fStack_e0,afStack_dc);
  uStack_a0 = lbl_821AAD20;
  uStack_9c = lbl_821AAD20;
  uStack_98 = lbl_821AAD20;
  uStack_94 = lbl_821AAD20;
  uStack_90 = lbl_821AAD20;
  uStack_84 = lbl_821AAD20;
  uStack_74 = lbl_821AAD20;
  uStack_68 = lbl_821AAD20;
  uStack_58 = lbl_821AAD20;
  uStack_48 = lbl_821AAD20;
  uStack_44 = lbl_821AAD20;
  uStack_38 = lbl_821AAD20;
  uStack_34 = lbl_821AAD20;
  fStack_78 = param_1[3];
  fStack_c8 = -fStack_78;
  fStack_cc = fStack_78 * (fStack_e0 / afStack_dc[0]);
  fStack_30 = param_1[2];
  fStack_8c = -fStack_30;
  fStack_c4 = param_1[1] * fStack_78 * (fStack_e0 / afStack_dc[0]);
  fStack_b4 = -fStack_cc;
  fStack_d0 = -fStack_c4;
  fStack_c0 = fStack_cc;
  fStack_bc = fStack_c8;
  fStack_b8 = fStack_d0;
  fStack_b0 = fStack_c8;
  fStack_ac = fStack_c4;
  fStack_a8 = fStack_b4;
  fStack_a4 = fStack_c8;
  fStack_88 = fStack_c8;
  fStack_80 = fStack_c4;
  fStack_70 = fStack_c4;
  fStack_64 = fStack_78;
  fStack_60 = fStack_cc;
  fStack_54 = fStack_c8;
  fStack_50 = fStack_cc;
  fStack_40 = fStack_c8;
  fn_82861078(&fStack_d0,param_2,0xfc,0xfc,param_3);
  return;
}

